<a href="https://colab.research.google.com/github/AnthonyAngatia/ML-Group-Final-Task/blob/main/Feature_Selection_%26_Regression_using_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Machine Learning Group Task 1**:Feature Selection & Regression using ANN

## Group members
Harry Karani

Stephanie Mboya

Angatia Anthony

In [ ]:
!pip install category_encoders

Requirement already satisfied: category_encoders in /usr/local/lib/python3.7/dist-packages (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (0.5.1)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (1.19.5)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (1.4.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (0.10.2)
Requirement already satisfied: pandas>=0.21.1 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (1.1.5)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (0.22.2.post1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.21.1->category_encoders) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.21.1->category_encoders) (2018.9)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from patsy>=0.5.1->category_encoders) (1.15.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.0.1)

In [ ]:
import pandas as pd
# To get the L1 embeddings
from sklearn.linear_model import LassoCV
from keras.models import Sequential
from keras.layers import Dense
# To normalize the data
from sklearn.preprocessing import PowerTransformer

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ICSY4S1-ML-Notebooks/Housing Pricing.csv')

In [ ]:
data.head()

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 77 columns]

In [ ]:
data.shape

(1460, 77)

**Removing useless columns and Null values**

In [ ]:
data.drop('Id',axis=1,inplace=True)

In [ ]:
data.isna().any()

MSSubClass       False
MSZoning         False
LotFrontage       True
LotArea          False
Street           False
                 ...
MoSold           False
YrSold           False
SaleType         False
SaleCondition    False
SalePrice        False
Length: 76, dtype: bool

In [ ]:
features_with_missing=list(data.columns[data.isna().any()])
features_with_missing

['LotFrontage',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond']

In [ ]:
data.dropna(axis=1,thresh=0.5*(len(data)),inplace=True)
data.shape

(1460, 76)

In [ ]:
f_fill = features_with_missing

In [ ]:
for feature in f_fill:
  data[feature].fillna(method='ffill', inplace=True)

**Encoding**

In [ ]:
original_features=list(data.columns)
len(original_features)

76

In [ ]:
cat_data=data.select_dtypes(include=['object']).copy()
cat_data.head()

  MSZoning Street LotShape  ... PavedDrive SaleType SaleCondition
0       RL   Pave      Reg  ...          Y       WD        Normal
1       RL   Pave      Reg  ...          Y       WD        Normal
2       RL   Pave      IR1  ...          Y       WD        Normal
3       RL   Pave      IR1  ...          Y       WD       Abnorml
4       RL   Pave      IR1  ...          Y       WD        Normal

[5 rows x 39 columns]

In [ ]:
cat_features=list(cat_data.columns)
cat_features

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [ ]:
numerical_features = list(set(original_features) - set(cat_features))
nominal_features = ['MSZoning','LandContour','LotConfig','Neighborhood']
ordinal_features = list(set(cat_features) - set(nominal_features))
target = ['SalePrice']

In [ ]:
for feature in ordinal_features:
  data[feature]=(data[feature].astype('category')).cat.codes
df_ordinal_features = data[ordinal_features]

In [ ]:
df_nominal_features=pd.get_dummies(data[nominal_features])

In [ ]:
df_numerical_features=data[numerical_features]

In [ ]:
data_encoded=pd.concat([df_numerical_features,df_nominal_features,df_ordinal_features],axis=1)

In [ ]:
data_encoded.head()

   1stFlrSF  GrLivArea  TotalBsmtSF  ...  ExterCond  BsmtFinType2  BsmtQual
0       856       1710          856  ...          4             5         2
1      1262       1262         1262  ...          4             5         2
2       920       1786          920  ...          4             5         2
3       961       1717          756  ...          4             5         3
4      1145       2198         1145  ...          4             5         2

[5 rows x 111 columns]

**Tranforming the data**

In [ ]:
# X_tranformed = PowerTransformer().fit_transform(data_encoded)
# X_tranformed

/usr/local/lib/python3.7/dist-packages/numpy/core/_methods.py:205: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)

array([[-0.79962416,  0.52853108, -0.40402913, ...,  0.37261738,
         0.3612733 , -0.56597312],
       [ 0.42915139, -0.38275482,  0.50817658, ...,  0.37261738,
         0.3612733 , -0.56597312],
       [-0.56853311,  0.6591119 , -0.25378739, ...,  0.37261738,
         0.3612733 , -0.56597312],
       ...,
       [ 0.24033765,  1.47117997,  0.26975485, ..., -2.68399614,
         0.3612733 ,  1.0029806 ],
       [-0.06516339, -0.85478753,  0.10602791, ...,  0.37261738,
        -2.52983479,  1.0029806 ],
       [ 0.41429283, -0.39703654,  0.49531516, ...,  0.37261738,
        -2.85746499,  1.0029806 ]])

**L1 feature selection**

In [ ]:
df_X = data_encoded.drop('SalePrice', axis=1)
df_y = data[target]

# X_array = df_X.to_numpy()
# y_array = df_y.to_numpy()

regressor=LassoCV()
regressor.fit(df_X,df_y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:1088: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LassoCV(alphas=None, copy_X=True, cv=None, eps=0.001, fit_intercept=True,
        max_iter=1000, n_alphas=100, n_jobs=None, normalize=False,
        positive=False, precompute='auto', random_state=None,
        selection='cyclic', tol=0.0001, verbose=False)

In [ ]:
print(regressor.coef_)

[ 0.00000000e+00  6.44015960e+01  3.32992607e+01  0.00000000e+00
  0.00000000e+00 -0.00000000e+00 -0.00000000e+00  1.86340906e+00
  0.00000000e+00 -0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00  3.10812490e+02 -0.00000000e+00  6.80319349e+01
  1.21561105e+01  0.00000000e+00  0.00000000e+00  2.94340726e+01
  0.00000000e+00  0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  2.87580260e-01  3.77611565e+01  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00  1.14366014e+02
 -1.38502215e-01  0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00]

In [ ]:
coef_col = pd.Series(regressor.coef_,index=df_X.columns)
print(coef_col)
print()

sorted_coef = coef_col.sort_values()
print(sorted_coef)

1stFlrSF         0.000000
GrLivArea       64.401596
TotalBsmtSF     33.299261
BsmtFullBath     0.000000
OverallQual      0.000000
                  ...
Electrical       0.000000
LandSlope        0.000000
ExterCond        0.000000
BsmtFinType2     0.000000
BsmtQual        -0.000000
Length: 110, dtype: float64

MiscVal          -0.138502
1stFlrSF          0.000000
MasVnrType        0.000000
Condition1        0.000000
KitchenQual      -0.000000
                   ...
MasVnrArea       37.761157
GrLivArea        64.401596
GarageArea       68.031935
YearRemodAdd    114.366014
YearBuilt       310.812490
Length: 110, dtype: float64

In [ ]:
selected_features = sorted_coef[coef_col != 0]
no_of_selected_features = sum(coef_col != 0)
rejected_features = sorted_coef[coef_col == 0]
no_of_rejected_features = sum(coef_col == 0)
total_features = no_of_selected_features + no_of_rejected_features
print("L1 selected only ",no_of_selected_features," features out of ",total_features," from the transformed dataset ")
print(selected_features.index)
print()
print(rejected_features)

L1 selected only  11  features out of  110  from the transformed dataset
Index(['MiscVal', 'LotArea', '2ndFlrSF', 'BsmtFinSF1', 'WoodDeckSF',
       'TotalBsmtSF', 'MasVnrArea', 'GrLivArea', 'GarageArea', 'YearRemodAdd',
       'YearBuilt'],
      dtype='object')

1stFlrSF           0.0
MasVnrType         0.0
Condition1         0.0
KitchenQual       -0.0
FireplaceQu       -0.0
                  ...
LandContour_Bnk   -0.0
MSZoning_RM       -0.0
MSZoning_RL        0.0
MSZoning_RH       -0.0
MSZoning_FV        0.0
Length: 99, dtype: float64

**Building and evaluating model**

In [ ]:
df_X_selected_features = df_X[selected_features.index]
df_X_selected_features
# standardize the data
X_array_selected_features = PowerTransformer().fit_transform(df_X_selected_features)
X_array_selected_features

y_array = df_y.to_numpy()

In [ ]:
# split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_array_selected_features, y_array, test_size=0.3, random_state=42)

In [ ]:
model=Sequential()
model.add(Dense(32, input_dim=11, kernel_initializer='normal', activation='relu'))
model.add(Dense(1, kernel_initializer='normal'))
model.compile(loss='mean_squared_error', optimizer='adam' metrics=['accuracy'])

history = model.fit(X_train, y_train, verbose=0, epochs=50)

In [ ]:
model.summary

           loss
0  3.899693e+10
1  3.875587e+10
2  3.825102e+10
3  3.744522e+10
4  3.635014e+10